networks:
  primary:
    driver: "bridge"
    ipam:
      config:
        - subnet: "10.0.0.0/28"

services:
  pihole:
    container_name: "pihole"
    hostname: "pihole"
    image: "pihole/pihole:2025.03.0"
    restart: "unless-stopped"
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      #- "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      VIRTUAL_HOST: "pihole.raspberrypi.local"
      VIRTUAL_PORT: "80"
      ServerIP: "192.168.1.100"
      TZ: "America/Los_Angeles"
    volumes:
      - "/mnt/external/data/pihole/data/:/etc/pihole/"
      - "/mnt/external/data/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- "NET_ADMIN"
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- "SYS_TIME"
      # Optional, if Pi-hole should get some more processing time
      - "SYS_NICE"
    networks:
      primary:
        ipv4_address: "10.0.0.2"
    logging:
      driver: "journald"
    extra_hosts:
      - "raspberrypi.local:192.168.1.100"
      - "pihole.raspberrypi.local:192.168.1.100"
      - "syncthing.raspberrypi.local:192.168.1.100"
      - "zigbee2mqtt.raspberrypi.local:192.168.1.100"
      - "homeassistant.raspberrypi.local:192.168.1.100"

  nginx-proxy:
    container_name: "nginx-proxy"
    hostname: "nginx-proxy"
    image: "nginxproxy/nginx-proxy:1.7-alpine"
    restart: "always"
    ports:
      - "80:80/tcp"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/mnt/external/data/nginx-proxy/certs/:/etc/nginx/certs/"
      - "/mnt/external/data/nginx-proxy/dhparam/:/etc/nginx/dhparam/"
    networks:
      primary:
        ipv4_address: "10.0.0.3"
    dns:
      - "10.0.0.2"
    logging:
      driver: "journald"
    depends_on:
      - "pihole"

  syncthing:
    container_name: "syncthing"
    hostname: "syncthing"
    restart: "unless-stopped"
    image: "syncthing/syncthing:1.29"
    ports:
      - "22000:22000"
      - "8384:8384"
    environment:
      VIRTUAL_HOST: "syncthing.raspberrypi.local"
      VIRTUAL_PORT: "8384"
    networks:
      primary:
        ipv4_address: "10.0.0.4"
    volumes:
      - "/mnt/external/data/syncthing/:/var/syncthing/"
    dns:
      - "10.0.0.2"
    logging:
      driver: "journald"
    depends_on:
      - "pihole"

  #grafana:
  #  container_name: "grafana"
  #  hostname: "grafana"
  #  image: "grafana/grafana:7.2.1"
  #  restart: "unless-stopped"
  #  ports:
  #    - "3000:3000/tcp"
  #  environment:
  #    VIRTUAL_HOST: "grafana.raspberrypi.local"
  #    VIRTUAL_PORT: "3000"
  #    GF_INSTALL_PLUGINS: "grafana-piechart-panel"
  #    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/Home.json"
  #  volumes:
  #    - "grafana-data:/var/lib/grafana"
  #    - "./config/grafana/provisioning:/etc/grafana/provisioning" # :ro ?
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.4"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"
  #    - "prometheus"
  #    - "loki"

  #portainer:
  #  container_name: "portainer"
  #  hostname: "portainer"
  #  image: "portainer/portainer-ce:2.0.0-alpine"
  #  restart: "unless-stopped"
  #  ports:
  #    - "8000:8000"
  #    - "9000:9000"
  #  environment:
  #    VIRTUAL_HOST: "portainer.raspberrypi.local"
  #    VIRTUAL_PORT: "9000"
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock"
  #    - "portainer-data:/data"
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.5"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"

  #telegraf:
  #  container_name: "telegraf"
  #  hostname: "telegraf"
  #  image: "telegraf:1.15"
  #  command: "--config-directory /etc/telegraf/telegraf.d"
  #  restart: "always"
  #  ports:
  #    - "9273:9273"
  #  environment:
  #    VIRTUAL_HOST: "telegraf.raspberrypi.local"
  #    VIRTUAL_PORT: "9273"
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock"
  #    - "./config/telegraf:/etc/telegraf:ro"
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.6"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"

  #prometheus:
  #  container_name: "prometheus"
  #  hostname: "prometheus"
  #  restart: "unless-stopped"
  #  image: "prom/prometheus:latest"
  #  ports:
  #    - "9090:9090"
  #  environment:
  #    VIRTUAL_HOST: "prometheus.raspberrypi.local"
  #    VIRTUAL_PORT: "9090"
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.8"
  #  volumes:
  #    - "prometheus-data:/prometheus"
  #    - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"

  #loki:
  #  container_name: "loki"
  #  hostname: "loki"
  #  restart: "unless-stopped"
  #  image: "grafana/loki:2.0.0"
  #  command: "-config.file=/etc/loki/loki.yml"
  #  ports:
  #    - "3100:3100"
  #  environment:
  #    VIRTUAL_HOST: "loki.raspberrypi.local"
  #    VIRTUAL_PORT: "3100"
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.9"
  #  volumes:
  #    - "loki-data:/loki"
  #    - "./config/loki/loki.yml:/etc/loki/loki.yml:ro"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"

  #promtail:
  #  container_name: "promtail"
  #  hostname: "promtail"
  #  restart: "unless-stopped"
  #  image: "grafana/promtail:2.0.0"
  #  command: "-config.file=/etc/promtail/promtail.yml"
  #  ports:
  #    - "9080:9080"
  #  environment:
  #    VIRTUAL_HOST: "promtail.raspberrypi.local"
  #    VIRTUAL_PORT: "9080"
  #  networks:
  #    primary:
  #      ipv4_address: "10.0.0.10"
  #  volumes:
  #    - "/var/log/journal/:/var/log/journal/:ro"
  #    - "/run/log/journal/:/run/log/journal/:ro"
  #    - "/etc/machine-id:/etc/machine-id:ro"
  #    - "./config/promtail/promtail.yml:/etc/promtail/promtail.yml:ro"
  #  dns:
  #    - "10.0.0.2"
  #  logging:
  #    driver: "journald"
  #  depends_on:
  #    - "pihole"
  #    - "loki"

  mqtt:
    container_name: "mqtt"
    hostname: "mqtt"
    restart: "unless-stopped"
    image: "eclipse-mosquitto:2.0"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
    #environment:
    #  VIRTUAL_HOST: "mqtt.raspberrypi.local"
    #  VIRTUAL_PORT: "9080"
    networks:
      primary:
        ipv4_address: "10.0.0.11"
    volumes:
      - "/mnt/external/data/mqtt:/mosquitto"
    dns:
      - "10.0.0.2"
    logging:
      driver: "journald"
    depends_on:
      - "pihole"


  zigbee2mqtt:
    container_name: "zigbee2mqtt"
    hostname: "zigbee2mqtt"
    restart: "unless-stopped"
    image: "koenkk/zigbee2mqtt:1.42.0"
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: "zigbee2mqtt.raspberrypi.local"
      VIRTUAL_PORT: "8080"
      TZ: "America/Los_Angeles"
    networks:
      primary:
        ipv4_address: "10.0.0.12"
    volumes:
      # zigbee2mqtt will use configuration.example.yaml as a template to generate configuration.yaml, this allows us to keep the initial configuration versioned
      - "./config/zigbee2mqtt/configuration.yaml:/app/configuration.example.yaml:ro"
      - "/mnt/external/data/zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"
    dns:
      - "10.0.0.2"
    logging:
      driver: "journald"
    depends_on:
      - "pihole"
      - "mqtt"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  homeassistant:
    container_name: "homeassistant"
    hostname: "homeassistant"
    restart: "unless-stopped"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    environment:
      VIRTUAL_HOST: "homeassistant.raspberrypi.local"
      VIRTUAL_PORT: "8123"
    networks:
      primary:
        ipv4_address: "10.0.0.13"
    volumes:
      - "/mnt/external/data/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    dns:
      - "10.0.0.2"
    logging:
      driver: "journald"
    depends_on:
      - "mqtt"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true
