{
 "title": "Computers",
 "description": "Overview of computers.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": "label_values(host)" },
   { "name": "disk", "query": "label_values(name)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{host=\"$Server\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_idle{host=\"$Server\", cpu=\"cpu-total\"} * -1 + 100"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temp_temp{host=\"$Server\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$Server\"}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$Server\", path=\"/etc/telegraf\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Percent(%)" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_user{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_nice{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "Nice"
    },
    {
     "expr": "cpu_usage_irq{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "Interupt"
    },
    {
     "expr": "cpu_usage_iowait{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "Wait"
    },
    {
     "expr": "cpu_usage_softirq{host=\"$Server\", cpu=\"cpu-total\"}",
     "legendFormat": "SoftIRQ"
    }
   ]
  },
  {
   "title": "CPU Usage & Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree", "label": "CPU Temperature Degrees *C" }
   ],
   "targets": [
    {
     "expr": "temp_temp{host=\"$Server\", sensor=\"cpu_thermal_input\"}",
     "legendFormat": "CPU Temperature"
    },
    {
     "expr": "cpu_usage_idle{host=\"$Server\", cpu=\"cpu-total\"} * -1 + 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=\"$Server\"}",
     "legendFormat": "1 Minute Average"
    },
    {
     "expr": "system_load5{host=\"$Server\"}",
     "legendFormat": "5 Minute Average"
    },
    {
     "expr": "system_load15{host=\"$Server\"}",
     "legendFormat": "15 Minute Average"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=\"$Server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_buffered{host=\"$Server\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "mem_cached{host=\"$Server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mem_free{host=\"$Server\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processes Forked & Total Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Proccesses Forked" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_processes_forked{host=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Processes Forked"
    },
    {
     "expr": "processes_total_threads{host=\"$Server\"}",
     "legendFormat": "Total Threads"
    }
   ]
  },
  {
   "title": "Interrupts & Context Swtiches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_interrupts{host=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "rate(kernel_context_switches{host=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Process Count" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{host=\"$Server\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "processes_running{host=\"$Server\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "processes_sleeping{host=\"$Server\"}",
     "legendFormat": "Sleeping"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=\"$Server\", name=~\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{host=\"$Server\", name=~\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}